spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: solicitudes-service
          uri: http://solicitudes-service:8081
          predicates:
            - Path=/solicitudes/**,/rutas/**,/tramos/**
        - id: logistica-service
          uri: http://logistica-service:8082
          predicates:
            - Path=/depositos/**,/camiones/**
        - id: tarifas-service
          uri: http://tarifas-service:8083
          predicates:
            - Path=/tarifas/**
        - id: tracking-service
          uri: http://tracking-service:8084
          predicates:
            - Path=/tracking/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/transportista-realm/protocol/openid-connect/certs
          issuer-uri: http://keycloak:8080/realms/transportista-realm

server:
  port: 8000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
