spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: solicitudes-service
          uri: http://solicitudes-service:8081
          predicates:
            - Path=/api/solicitudes/**
          filters:
            - StripPrefix=2
        - id: logistica-service
          uri: http://logistica-service:8082
          predicates:
            - Path=/api/logistica/**
          filters:
            - StripPrefix=2
        - id: tarifas-service
          uri: http://tarifas-service:8083
          predicates:
            - Path=/api/tarifas/**
          filters:
            - StripPrefix=2
        - id: tracking-service
          uri: http://tracking-service:8084
          predicates:
            - Path=/api/tracking/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/transportista-realm


# URLs de los microservicios
services:
  solicitudes:
    url: http://solicitudes-service:8081
  logistica:
    url: http://logistica-service:8082
  tarifas:
    url: http://tarifas-service:8083
  tracking:
    url: http://tracking-service:8084

server:
  port: 8000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
